// Pipeline I/O + determinism primitives.
//
// Every byte the renderer emits MUST be reproducible across machines/CI for
// the byte-identical gate a consumer wires up (regen + `git diff --exit-code`).
// This module is the single authority for the non-determinism neutralizations:
//
//  - Ordering uses CODEPOINT (pure UTF-16 code-unit compare), NOT
//    Intl.Collator / String.prototype.localeCompare: ICU collation tables
//    differ across Node/OS builds and would break a byte-identical gate.
//    Token keys are ASCII kebab-case, so code-point order is total, obvious,
//    and platform-independent.
//  - Serialized objects are built in canonical insertion order and emitted
//    with a 2-space indent; V8 preserves string-key insertion order, so no
//    sort replacer is needed (ordered construction is the authority).
//  - All output is forced to LF with exactly one trailing newline.
//
// Banner text (the "GENERATED by ... DO NOT EDIT" prelude on the rendered
// CSS) is intentionally NOT provided here: it is project-level documentation
// — package name, regenerate command, cross-references — that the consumer
// owns and passes verbatim to `renderTokensCss({ header })`.

import { readFileSync } from 'node:fs';

/**
 * Pure UTF-16 code-unit comparator. Total order, ICU-independent — the only
 * sort allowed in the pipeline (see module header).
 */
export const CODEPOINT = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

/**
 * Read DESIGN.md from `path` and split off its YAML frontmatter block (verbatim).
 * @param {string} path absolute path to DESIGN.md
 */
export function readDesignMd(path) {
  const raw = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) {
    throw new Error(
      `${path}: YAML frontmatter block (--- … ---) not found at file start.`,
    );
  }
  return { raw, frontmatter: m[1] };
}

/** LF, exactly one trailing newline (Stage 4). */
export function normalizeText(text) {
  return `${text.replace(/\r\n/g, '\n').replace(/\n+$/, '')}\n`;
}

/** Deterministic JSON: ordered construction + 2-space + LF + one trailing \n. */
export function serializeJson(value) {
  return normalizeText(JSON.stringify(value, null, 2));
}
